name: Build BedWars2023

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests -B

    - name: Upload Plugin JAR
      uses: actions/upload-artifact@v3
      with:
        name: BedWars2023-1.8.8-Fixed
        path: |
          bedwars-plugin/target/BedWars*.jar
          !bedwars-plugin/target/original-*.jar
