name: Build BedWars2023 (Only Build JAR)

on:
  push:
    branches: [ master, main, production ]  # Adjust based on your branch name
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build plugin with Gradle (shadowJar)
        run: ./gradlew clean shadowJar --no-daemon --info

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: BedWars2023-Fixed-1.8.8
          path: bedwars-plugin/build/libs/*.jar
